[[section-system-scope-and-context]]
== Alcance y Contexto del Sistema

=== Contexto de Negocio

[plantuml,"Business Context Diagram",png]
----
left to right direction
skinparam actorStyle awesome
actor Usuario as g
package DeDe {

}
database BBDD
hexagon POD
cloud API
g --> DeDe
DeDe <--> POD
DeDe <--> BBDD
DeDe <--> API
----

El sistema permitirá al usuario hacer pedidos de los diferentes productos disponibles, pudiendo también, iniciar sesión con su propia cuenta mediante un proveedor de pods, que seguirá los principios SOLID. Dicho pod es quien se encarga de gestionar la información de los usuarios. Por otro lado, los datos de los productos serán almacenados por la base de datos.

* Usuario: persona interesado en la tienda que quiera realizar una compra y poder gestionar su propia cuenta
* DeDe: provee al usuario la interfaz necesaria para llevar a cabo todas las operaciones
* Pod: suministra a la aplicación la información descentralizada del usuario
* Base de datos: encargada de toda la persistencia de los datos que compondran la aplicación

=== Contexto Técnico

Como se ha mencionado anteriormente, la aplicación hará uso de la tecnología SOLID dirigida por Tim Berners-Lee para realizar un proyecto descentralizado. Esta proporcionará un pod a cada usuario permitiendo almacenar toda la información de cada uno, y se la proveerá a la aplicación.
Para la implementación del proyecto se utilizarán tecnologías como REACT, para el desarrollo Frontend, y la base de datos MongoDB, para todo lo relativo a la persistencia de datos.

|===
|Tecnología|Descripción
| React | Biblioteca escrita en JavaScript desarrollada por Facebook para la creación de interfaces de usuario.
| TypeScript | Lenguaje de programación libre y de código abierto desarrollado y mantenido por Microsoft. Es un superconjunto de JavaScript
| SOLID | Proyecto descentralizado cuyo principal objetivo es que el usuario tenga el control de su privacidad.
| MongoDB | Base de datos NoSQL open source que ofrece un modelo de datos flexible para organizar y almacenar todo tipo de datos
|===
