[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
Este apartado contendrá información detallada del funcionamiento de la aplicación y de como esta
se comportara ante los distintos escenarios que se pueden dar.

.Motivation
La motivación de este apartado consiste en ilustrar a los stakeholders sobre el funcionamiento de la aplicación,
de forma que los posibles usuarios que tenga la aplicación puedan aprender y familiarizarse con el funcionamiento de 
ésta rapidamente para que sus experiencias sean satisfactorias.



=== Escenario 1. Registrarse como un nuevo usuario
Para registrarse como nuevo usuario en la aplicación, tendrás que dar permiso al Pod con tus datos
para permitir al servicio conocer tus nombre, apellidos y direccion. Esto nos servirá para poder
calcular los gastos de envío propios de enviar un producto al domicilio del usuario


=== Escenario 2. Comenzar un nuevo pedido
Para comenzar un nuevo pedido, has de loggearte en la web, con los datos requeridos que previamente 
has proporcionado mediante el Pod, y comenzar a añadir productos a tu pedido



=== Escenario 3. Realizar un pedido
Se empezarán a añadir los productos deseados al pedido y una vez se hayan añadido todos 
los productos necesarios, podrás finalizar el pedido y se enviará a la direccion proporcionada
por el pod
