[[section-runtime-view]]
== Runtime View

=== Escenario 1. Registrarse como un nuevo usuario
Para registrarse, el usuario deberá rellenar el formulario correspondiente. Una vez hecho, se guardarán en 
la base de datos solo los datos necesarios. El resto de datos personales serán almacenados en el POD.

[plantuml,"escenario1",png]
----
actor Usuario
entity Webapp
entity Restapi
database POD
database MongoDB
Usuario -> Webapp: Rellenar formulario signup
Webapp -> Restapi: Envía los datos
Restapi -> POD: Envía datos personales
Restapi -> MongoDB: Envía datos necesarios
Webapp <-- Restapi: Devuelve token
Usuario <- Webapp: Notifica al usuario
----

=== Escenario 2. Iniciar sesión

[plantuml,"escenario2",png]
----
actor Usuario
entity Webapp
entity Restapi
database POD
database MongoDB
Usuario -> Webapp: Rellenar formulario login
Webapp -> Restapi: Envía los datos
Restapi -> POD: Valida los datos
POD --> Restapi: Devuelve los datos privados
Restapi -> MongoDB: Valida los datos
MongoDB --> Restapi: Devuelve los datos correspondientes
Restapi --> Webapp: Devuelve token 
Webapp -> Usuario: Notifica al usuario
----

El usuario deberá rellenar el formulario correspondiente para iniciar sesión. Los datos serán enviados y validados y finalmente se le notificará al usuario si ha introducido los datos correctamente.

=== Escenario 3. Realizar un pedido
Se empezarán a añadir los productos deseados al pedido y una vez se hayan añadido todos 
los productos necesarios, podrás finalizar el pedido y se enviará a la direccion proporcionada
por el pod.

=== Escenario 4. Vista de productos
Una vez en la vista de tienda, se pueden realizar varias operaciones, como ver detalles, filtrar 
productos, buscar por nombre y añadir al carrito.
[plantuml,"vistaProductos",png]
----
actor Usuario
participant Tienda
participant Carrito
Usuario -> Tienda: accede
Usuario -> Tienda: aplica filtros
Usuario -> Tienda: detalles producto
Tienda -> Tienda: mostrar detalles
Usuario -> Tienda: añadir carrito
Tienda -> Carrito: añade producto
----

=== Escenario 5. Información sobre pods
Desde la vista de registro se puede navegar hasta una pantalla que contiene información sobre
los pods que se utilizan en la aplicación.
[plantuml,"vistaPods",png]
----
actor Usuario
participant Sing_Up
participant Info_Pods
Usuario -> Sing_Up: accede
Usuario -> Sing_Up: info Pods
Sing_Up -> Info_Pods: redirige
Usuario -> Info_Pods: volver a sing up
Info_Pods -> Sing_Up: redirige
----

